# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    #config.vm.box = "centos/1805"
    config.vm.box = "centos/7.1902.01"
    config.vm.box_check_update = false

    config.vm.provider "libvirt" do |lv, override|
        lv.driver = "kvm"
        lv.memory = 10240
        lv.cpus = 2
        lv.storage_pool_name = 'linux'
        lv.input :type => "tablet", :bus => "usb"
    end
    
    # A machine configuration for a quick start without bundled files
    config.vm.define "quickstart", primary: true, autostart: false do |infra|
        infra.vm.hostname = "infra.demo.com"
        config.vm.network "private_network", ip: "192.168.121.101", auto_config: false
        config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [ ".git" ]
        config.vm.synced_folder "../../", "/soestack/", type: "rsync", rsync__exclude: [".git", "*.raw", "*.qcow2", "*.iso", "usb", "bundled" ] 
        config.vm.provision "shell", inline: "/soestack/provision/vagrant/provision.sh quickstart.cfg"
    end

    config.vm.define "standalone", primary: false, autostart: false do |infra|
        infra.vm.hostname = "infra.demo.com"
        config.vm.network "private_network", ip: "192.168.121.101", auto_config: false
        config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [ ".git" ]
        config.vm.synced_folder "../../", "/soestack/", type: "rsync", rsync__exclude: [".git", "*.raw", "*.qcow2", "*.iso", "usb", "bundled" ] 
        config.vm.synced_folder "../../bundled", "/e/bundled/", type: "rsync", rsync__exclude: [ "*prior*","*.rpm", "repodata","*.tar","*.iso" ] 
        config.vm.provision "shell", inline: "/soestack/provision/vagrant/provision.sh standalone.cfg"
    end

end

