variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - venv/

#before_script:
#  - echo "Before script section"

#after_script:
#  - echo "After script section"

bash-syntax:
    image: bash:latest
    stage: test
    script:
        - for f in provision/{common,common/lib,kickstart,kickstart/lib,vagrant,vagrant/lib,docker,docker/lib}/*.sh; do echo "Check ${f}"; bash -n "${f}" 2>&1 ;done
    tags:
        - docker

docker-test-centos:
    image: centos:7.6.1810
    stage: test
    script:
        - pwd
        - ls -l
        - find . -name "*.sh"
        - $PWD/provision/docker/provision.sh docker.cfg
        - $PWD/provision/common/provision.sh
    tags:
        - docker
    only:
        - docker-testing
    

docker-test-busybox:
    image: busybox:latest
    stage: test
    script:
        - $PWD/provision/common/provision.sh
    tags:
        - docker
    only:
        - docker-testing
      
# NOTE this job must be called pages, in order to be used for Gitlab Pages
pages:
    image: python:3
    stage: deploy
    script:
        - python3 -m venv venv
        - . venv/bin/activate
        - pip install --upgrade pip
        - pip install sphinx
        - sphinx-build docs public
    tags:
        - docker
    artifacts:
        paths:
            - public
