#!/bin/bash
prefix="/soestack/salt/state/"
name="${1//./\/}"
path="${prefix}/${name}"
main_sls="${path}.sls"
init_sls="${path}/init.sls"
selected=""
for selected in "${main_sls}" "${init_sls}"
do
    if [[ -f "${selected}" ]]
    then
        salt-call slsutil.renderer "${selected}" jinja
        break
    fi
done
