project = 'SoeStack'
copyright = '2019, Chris Sincock'
author = 'Chris Sincock'
release = '2.0'
extensions = [ ]
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'alabaster'
html_static_path = ['_static']
html_domain_indices = False
